### ISSUE TITLE
For Emissive Intensity settings

### ISSUE THREAD

**Issue by penti-jp** [ray-cast/ray-mmd#31]
In setting of EmissiveIntensity, it seems the decimal point are truncated.
Setting of the decimal point is, because it was frequently used in the now of implementation, troubled.
From 1.31, or is to change the implementation will there is a reason.

**Comment by ray-cast** [comment]
Because of gbuffer-space limitation that caused a floating-point of the emissiveIntensity would only have two decimal points.
So, that emissiveIntensity is encoded into integer by intensity * 100 and another parameter is encoded to decimal part. and, well, it will decoded internally by integer part / 100 as emissiveIntensity parameter

But now it's fixed in dev version and stored it in a single channel

**Comment by ray-cast** [comment]
It now has 3 decimal points for a emissiveIntensity.
download 140beta again and copy 3 files to overwrite old file:
Materials/material_common.fxsub
Materials/material_common_2.0.fxsub
Shader/gbuffer.fxsub

**Comment by penti-jp** [comment]
gbuffer - space If it is limited, that is unavoidable. understood.
In the Dev version, as it stands, we have understood that there is no change, that.
Still 140 beta, thank you for changing gbuffer, thank you! !

Is it okay to tell this on Twitter?

**Comment by penti-jp** [comment]
I checked the operation at 140 beta. It is more than expected, so I am surprised. Thank you very much.
