### ISSUE TITLE
How Can I Do Toon?

### ISSUE THREAD

**Issue by mmdlifeyt** [ray-cast/ray-mmd#41]
Hi It's not a issue but I need to know that sorry for disturb how can I do toon with raymmd like

![](https://raw.githubusercontent.com/ray-cast/ray-mmd/developing/Shader/screenshots/screen3.png)

**Comment by ray-cast** [comment]
Hmm, Hard to say

Because it needs to write a lot of material for each subset of model.

To deal with this picture out, I've done these things:
* Sets the `OUTLINE_QUALITY` to 3
* Sets the `TOON_ENABLE` to 2
* Assign a `skylighting_none.fx` to `skybox.pmx` in the `EnvLighting` tab
* Assign a orange wireframe to part subsets of model in the `OutlineMap` tab
* Write Toon-materials for each subset of model 
* This scene is based on `Toon-Based Shading (CUSTOM_ENABLE 9)` and model is a `Cel Shading (CUSTOM_ENABLE 8)`

**Comment by mmdlifeyt** [comment]
Thanks ❤️
