### ISSUE TITLE
About Extension's SubModules

### ISSUE THREAD

**Issue by penti-mmd** [ray-cast/ray-mmd#42]
Extension's SubModules will not be inculuded in the ray-mmd package? Developing Zip file does not contain the updated SubModules. Is SubModules an understanding that you should DL as much as you need?

**Comment by ray-cast** [comment]
Github is under the [Git](https://git-scm.com/) and github subtree allows to adding any repository from another [Git](https://git-scm.com/) webside as a submodules, such as: https://bitbucket.org/product, https://about.gitlab.com/

That would be wasting bandwidth of the Github server, when you download archive from github page.
Because Github is one of several ways Git servers can manage git projects.

**Comment by penti-mmd** [comment]
Thank U for your answer. I understand that there is a possibility that it can not be done due to specifications. Since I don’t have a problem with individual DL, I will Close this Issue. Thank U so very much.
