### ISSUE TITLE
How to use groundfog?

### ISSUE THREAD

**Issue by sleepymanakete** [ray-cast/ray-mmd#78]
Hi, i couldn't find a guide for how to use the groundfog and i would like to use it. Can someone please explain?

**Comment by Syloid** [comment]
Hi Summer, I'm Red, 

Here's how I do it whenever I use it:

- Add the _GroundFog.pmx_ from the Fog folder into MMD.

- With the controller, specify which colour the Fog will display. I usually go for `1.0` RGB (white), If you leave it by default it will be black.

(Note that at this point you still won't see anything, it's fine.)

- In order to make the Fog visible you **must** put _Height+_ and _Density+_ at least up to `0.01`.

- The only thing left you might do is play a bit with the _Height+, Density+_ and _Range+_ parameters as your liking.

If you want to make that Controller's ugly rectangle disappear: 

![ajdkal](https://user-images.githubusercontent.com/33935297/42225915-ef4b077c-7edd-11e8-983a-60115cec4e1e.png)

**Comment by sleepymanakete** [comment]
thank you!
